// /api/volunteer — public volunteer sign-up, no account needed: the site's
// volunteer dialog, and each event's own page at /events/<slug>/volunteer/.
//   GET  — the published events that have not happened yet, each with the
//          questions of its own volunteer form (null when it asks the site's
//          default ones), plus those default questions (the form_templates
//          row of kind 'volunteer' marked default, 0035). Never says anything
//          about volunteers.
//   GET ?event=<slug> — that one event, for its page. With a valid
//          Authorization: Bearer <supabase access token>, also the caller's
//          email and their sign-up for it, so the page can show it as it
//          stands. Signed out, nothing about any email.
//   POST — one event_volunteers row per event the person picked (none picked =
//          a single row with event_id null, "wherever needed"). The answers are
//          checked against the form in effect — one event picked that has its
//          own questions asks those, anything else asks the default — and
//          MERGED into the answers the row already holds. A second submission
//          for the same (event, email) updates the name, phone and message but
//          keeps created_at, the first sign-up time.
// With a token the row is linked to the account (member_id) only when the form
// email is the account's own login email — the same rule as /api/event-register,
// so a signed-in visitor cannot pin someone else's address to their account. A
// bad or expired token is treated as signed out, never as an error.
// event_volunteers is server-only (0021): read and written here, by
// /api/event-register and by /api/admin/event-volunteers, with the service-role
// key.
import { json, bad, sb, sendEmail } from './_lib.js';
import { validateAnswers, choiceAnswerLabels } from './_event-form.js';
import { esc, emailLogo, volunteerConfirmation } from './_event-emails.js';
import {
  optionalUser,
  EMAIL_RE,
  upcomingEventFilters,
  saveVolunteer,
  questionsOf,
  defaultVolunteerQuestions,
  priorVolunteer,
  mergedAnswers,
} from './_volunteers.js';
import { requireHuman, turnstileToken } from './_turnstile.js';

const EVENT_COLUMNS =
  'id,slug,title,title_zh,description,description_zh,starts_at,ends_at,location,volunteer_questions';
const MAX_EVENTS = 20;
// Slugs are generated by slugify() in /api/admin/events, so anything else
// cannot name an event — and keeping the charset tight is what makes it safe
// to put the slugs into a PostgREST `in.(…)` list, whose quoting rules differ
// from a plain eq filter.
const SLUG_RE = /^[a-z0-9-]{1,64}$/;

// An event as the dialog and the page see it. `questions` is the event's own
// volunteer form, or null: it asks the default questions sent alongside.
const publicEvent = (e) => ({
  slug: e.slug,
  title: e.title,
  title_zh: e.title_zh ?? null,
  description: e.description ?? null,
  description_zh: e.description_zh ?? null,
  starts_at: e.starts_at,
  ends_at: e.ends_at ?? null,
  location: e.location ?? null,
  questions: questionsOf(e.volunteer_questions),
});

export async function onRequestGet({ request, env }) {
  const slug = (new URL(request.url).searchParams.get('event') || '').trim();
  if (slug && !SLUG_RE.test(slug)) return bad('Event not found.', 404);
  try {
    const DB = sb(env);
    const filters = upcomingEventFilters();
    if (slug) filters.push(`slug=eq.${slug}`);
    const [{ rows }, questions] = await Promise.all([
      DB.select('events', {
        columns: EVENT_COLUMNS,
        filters,
        order: 'starts_at.asc',
        limit: MAX_EVENTS,
      }),
      defaultVolunteerQuestions(DB),
    ]);
    const events = rows.map(publicEvent);
    if (!slug) return json({ events, questions });
    // The page for one event: a slug that names no open event is not found,
    // the same answer /api/event-register gives.
    if (!events.length) return bad('Event not found.', 404);

    const out = { events, questions, signed_in: false };
    const user = await optionalUser(request, env);
    if (!user) return json(out);
    // The sign-up is keyed on (event_id, email) only — never looked up by
    // account — so it follows the address the form would use.
    const email = String(user.email || '').toLowerCase();
    const row = email
      ? await priorVolunteer(DB, rows[0].id, email, 'name,phone,answers,created_at,updated_at')
      : null;
    return json({
      ...out,
      signed_in: true,
      email: user.email || null,
      signup: row
        ? {
            name: row.name,
            phone: row.phone ?? null,
            answers: row.answers && typeof row.answers === 'object' ? row.answers : {},
            created_at: row.created_at,
            updated_at: row.updated_at ?? null,
          }
        : null,
    });
  } catch (e) {
    return bad(e.message, 500);
  }
}

// The trimmed string, or null when it is empty. Longer than `max` -> undefined,
// which the caller turns into a 400.
function text(value, max) {
  const s = String(value ?? '').trim();
  if (s.length > max) return undefined;
  return s || null;
}

// The slugs the body asked for, de-duplicated and in the order given, or
// { error } when the list is unusable.
function wantedSlugs(value) {
  if (value == null || value === '') return { slugs: [] };
  if (!Array.isArray(value)) return { error: 'Invalid events.' };
  const slugs = [...new Set(value.map((s) => String(s ?? '').trim()).filter(Boolean))];
  if (slugs.length > MAX_EVENTS) return { error: 'Too many events selected.' };
  return { slugs };
}

export async function onRequestPost({ request, env }) {
  let b;
  try {
    b = await request.json();
  } catch {
    return bad('invalid JSON');
  }
  if (!b || typeof b !== 'object') return bad('invalid JSON');
  if (b._hp) return json({ ok: true }); // honeypot: silently accept bots

  const name = text(b.name, 120);
  if (!name) return bad('Enter your name.');

  const email = String(b.email ?? '')
    .trim()
    .toLowerCase();
  if (email.length > 254 || !EMAIL_RE.test(email)) return bad('Enter a valid email address.');

  const phone = text(b.phone, 40);
  if (phone === undefined) return bad('That phone number is too long.');
  const message = text(b.message, 2000);
  if (message === undefined) return bad('That message is too long.');

  const wanted = wantedSlugs(b.events);
  if (wanted.error) return bad(wanted.error);
  const { slugs } = wanted;

  // Last gate before anything is read, written or sent: this endpoint mails a
  // CAACI-branded confirmation to whatever address it is given, so without it a
  // script could point it at a stranger, repeatedly. It sits after the field
  // checks above so a typo answers 400 without spending the visitor's token —
  // Turnstile tokens are single-use, and a burnt one means solving again.
  const human = await requireHuman(request, env, 'volunteer', turnstileToken(b));
  if (human.error) return human.error;

  try {
    const DB = sb(env);

    // Every slug must name a published event that has not happened yet — the
    // same list GET offers — so a stale or guessed slug is a plain 404-style
    // refusal rather than a row against an event nobody can pick.
    let events = [];
    if (slugs.length) {
      if (!slugs.every((s) => SLUG_RE.test(s))) return bad('Event not found.');
      const { rows } = await DB.select('events', {
        columns: EVENT_COLUMNS,
        filters: [...upcomingEventFilters(), `slug=in.(${slugs.join(',')})`],
        limit: MAX_EVENTS,
      });
      const bySlug = new Map(rows.map((r) => [r.slug, r]));
      if (slugs.some((s) => !bySlug.has(s))) return bad('Event not found.');
      events = slugs.map((s) => bySlug.get(s));
    }

    // The form in effect: exactly one event with its own questions asks those;
    // any other pick (none, several, or an event without its own) asks the
    // default. Answers to questions the form does not ask are dropped.
    const own = events.length === 1 ? questionsOf(events[0].volunteer_questions) : null;
    const questions = own ?? (await defaultVolunteerQuestions(DB));
    const checked = validateAnswers(questions, b.answers);
    if (checked.error) return bad(checked.error);
    const { answers } = checked;

    // Linked only when it is the account's own address (see the file header).
    const user = await optionalUser(request, env);
    const linked = !!user?.id && String(user.email || '').toLowerCase() === email;
    const memberId = linked ? user.id : null;

    // One row per chosen event; with none chosen, the single event_id null
    // "wherever needed" row. Each row's stored answers are read first so the
    // new ones merge into them instead of replacing them.
    const ids = events.length ? events.map((e) => e.id) : [null];
    let already = false;
    let createdAt = null;
    for (const eventId of ids) {
      const prior = await priorVolunteer(DB, eventId, email, 'answers,created_at');
      if (prior) already = true;
      const rows = await saveVolunteer(DB, {
        eventId,
        name,
        email,
        phone,
        message,
        source: 'volunteer',
        memberId,
        answers: mergedAnswers(prior?.answers, answers),
      });
      const at = prior?.created_at ?? (Array.isArray(rows) ? rows[0]?.created_at : null) ?? null;
      if (at && (!createdAt || at < createdAt)) createdAt = at;
    }

    const picked = events.map((e) => ({
      slug: e.slug,
      title: e.title,
      title_zh: e.title_zh ?? null,
    }));
    const origin = new URL(request.url).origin;
    await notify(env, { name, email, phone, message, events: picked, questions, answers });
    try {
      const { subject, html } = volunteerConfirmation({
        origin,
        logo: emailLogo(env.SUPABASE_URL),
        events: picked,
      });
      await sendEmail(env, { to: email, replyTo: env.NOTIFY_TO, subject, html });
    } catch {
      // The sign-up is saved; a lost thank-you must not fail the form.
    }

    return json({
      ok: true,
      events: picked,
      signed_in: !!user?.id,
      linked,
      already,
      created_at: createdAt,
    });
  } catch (e) {
    return bad(e.message, 500);
  }
}

// One line per answered question, for the staff notification only: the
// English label and the answer — option labels for a choice (plus the typed
// Other), the text itself otherwise — all escaped.
function answerLines(questions, answers) {
  return (questions || [])
    .filter((q) => answers && Object.hasOwn(answers, q.id))
    .map((q) => {
      const a = answers[q.id];
      let value;
      if (q.type === 'single' || q.type === 'multi') {
        const labels = choiceAnswerLabels(q, a, 'en').filter((l) => l !== 'Other');
        if (typeof a?.other === 'string') labels.push(`Other: ${a.other}`);
        value = labels.join(', ');
      } else {
        value = String(a);
      }
      return `<b>${esc(q.label_en)}:</b> ${esc(value)}`;
    });
}

// The staff notification. Unlike the volunteer's own thank-you this is sent to
// NOTIFY_TO only, so it carries what the volunteer typed — escaped, and with
// reply-to set to them so staff can answer in one click.
async function notify(env, { name, email, phone, message, events, questions, answers }) {
  try {
    const list = events.length
      ? events.map((e) => esc(e.title_zh ? `${e.title_zh} · ${e.title}` : e.title)).join('<br>')
      : 'Any event';
    const lines = answerLines(questions, answers);
    await sendEmail(env, {
      subject: `CAACI volunteer sign-up: ${name}`,
      replyTo: email,
      html:
        `<p><b>Name:</b> ${esc(name)}</p><p><b>Email:</b> ${esc(email)}</p>` +
        `<p><b>Phone:</b> ${esc(phone || '-')}</p>` +
        `<p><b>Events:</b><br>${list}</p>` +
        (lines.length ? `<p>${lines.join('<br>')}</p>` : '') +
        `<p><b>How they can help:</b><br>${esc(message || '-')}</p>`,
    });
  } catch {
    // The sign-up is saved; a lost notification must not fail the form.
  }
}
