// /api/volunteer — public volunteer sign-up, no account needed (the mirror's
// /volunteer/ page takes over the Divi contact form there).
//   GET  — the published events that have not happened yet, so the page can
//          offer them as checkboxes. Never says anything about volunteers.
//   POST — one event_volunteers row per event the person picked (none picked =
//          a single row with event_id null, "wherever needed"). A second
//          submission for the same (event, email) updates the name, phone and
//          message but keeps created_at, the first sign-up time.
// With a valid Authorization: Bearer <supabase access token> the row is linked
// to the account (member_id) only when the form email is the account's own
// login email — the same rule as /api/event-register, so a signed-in visitor
// cannot pin someone else's address to their account. A bad or expired token is
// treated as signed out, never as an error.
// event_volunteers is server-only (0021): read and written here, by
// /api/event-register and by /api/admin/event-volunteers, with the service-role
// key.
import { json, bad, sb, sendEmail } from './_lib.js';
import { esc, emailLogo, volunteerConfirmation } from './_event-emails.js';
import { optionalUser, EMAIL_RE, upcomingEventFilters, saveVolunteer } from './_volunteers.js';

const EVENT_COLUMNS = 'id,slug,title,title_zh,starts_at,ends_at,location';
const MAX_EVENTS = 20;
// Slugs are generated by slugify() in /api/admin/events, so anything else
// cannot name an event — and keeping the charset tight is what makes it safe
// to put the slugs into a PostgREST `in.(…)` list, whose quoting rules differ
// from a plain eq filter.
const SLUG_RE = /^[a-z0-9-]{1,64}$/;

const publicEvent = (e) => ({
  slug: e.slug,
  title: e.title,
  title_zh: e.title_zh ?? null,
  starts_at: e.starts_at,
  ends_at: e.ends_at ?? null,
  location: e.location ?? null,
});

export async function onRequestGet({ env }) {
  try {
    const { rows } = await sb(env).select('events', {
      columns: EVENT_COLUMNS,
      filters: upcomingEventFilters(),
      order: 'starts_at.asc',
      limit: MAX_EVENTS,
    });
    return json({ events: rows.map(publicEvent) });
  } catch (e) {
    return bad(e.message, 500);
  }
}

// The trimmed string, or null when it is empty. Longer than `max` -> undefined,
// which the caller turns into a 400.
function text(value, max) {
  const s = String(value ?? '').trim();
  if (s.length > max) return undefined;
  return s || null;
}

// The slugs the body asked for, de-duplicated and in the order given, or
// { error } when the list is unusable.
function wantedSlugs(value) {
  if (value == null || value === '') return { slugs: [] };
  if (!Array.isArray(value)) return { error: 'Invalid events.' };
  const slugs = [...new Set(value.map((s) => String(s ?? '').trim()).filter(Boolean))];
  if (slugs.length > MAX_EVENTS) return { error: 'Too many events selected.' };
  return { slugs };
}

export async function onRequestPost({ request, env }) {
  let b;
  try {
    b = await request.json();
  } catch {
    return bad('invalid JSON');
  }
  if (!b || typeof b !== 'object') return bad('invalid JSON');
  if (b._hp) return json({ ok: true }); // honeypot: silently accept bots

  const name = text(b.name, 120);
  if (!name) return bad('Enter your name.');

  const email = String(b.email ?? '')
    .trim()
    .toLowerCase();
  if (email.length > 254 || !EMAIL_RE.test(email)) return bad('Enter a valid email address.');

  const phone = text(b.phone, 40);
  if (phone === undefined) return bad('That phone number is too long.');
  const message = text(b.message, 2000);
  if (message === undefined) return bad('That message is too long.');

  const wanted = wantedSlugs(b.events);
  if (wanted.error) return bad(wanted.error);
  const { slugs } = wanted;

  try {
    const DB = sb(env);

    // Every slug must name a published event that has not happened yet — the
    // same list GET offers — so a stale or guessed slug is a plain 404-style
    // refusal rather than a row against an event nobody can pick.
    let events = [];
    if (slugs.length) {
      if (!slugs.every((s) => SLUG_RE.test(s))) return bad('Event not found.');
      const { rows } = await DB.select('events', {
        columns: EVENT_COLUMNS,
        filters: [...upcomingEventFilters(), `slug=in.(${slugs.join(',')})`],
        limit: MAX_EVENTS,
      });
      const bySlug = new Map(rows.map((r) => [r.slug, r]));
      if (slugs.some((s) => !bySlug.has(s))) return bad('Event not found.');
      events = slugs.map((s) => bySlug.get(s));
    }

    // Linked only when it is the account's own address (see the file header).
    const user = await optionalUser(request, env);
    const linked = !!user?.id && String(user.email || '').toLowerCase() === email;
    const memberId = linked ? user.id : null;

    // One row per chosen event; with none chosen, the single event_id null
    // "wherever needed" row.
    const ids = events.length ? events.map((e) => e.id) : [null];
    for (const eventId of ids) {
      await saveVolunteer(DB, {
        eventId,
        name,
        email,
        phone,
        message,
        source: 'volunteer',
        memberId,
      });
    }

    const picked = events.map((e) => ({
      slug: e.slug,
      title: e.title,
      title_zh: e.title_zh ?? null,
    }));
    const origin = new URL(request.url).origin;
    await notify(env, { name, email, phone, message, events: picked });
    try {
      const { subject, html } = volunteerConfirmation({
        origin,
        logo: emailLogo(env.SUPABASE_URL),
        events: picked,
      });
      await sendEmail(env, { to: email, replyTo: env.NOTIFY_TO, subject, html });
    } catch {
      // The sign-up is saved; a lost thank-you must not fail the form.
    }

    return json({ ok: true, events: picked, signed_in: !!user?.id, linked });
  } catch (e) {
    return bad(e.message, 500);
  }
}

// The staff notification. Unlike the volunteer's own thank-you this is sent to
// NOTIFY_TO only, so it carries what the volunteer typed — escaped, and with
// reply-to set to them so staff can answer in one click.
async function notify(env, { name, email, phone, message, events }) {
  try {
    const list = events.length
      ? events.map((e) => esc(e.title_zh ? `${e.title_zh} · ${e.title}` : e.title)).join('<br>')
      : 'Any event';
    await sendEmail(env, {
      subject: `CAACI volunteer sign-up: ${name}`,
      replyTo: email,
      html:
        `<p><b>Name:</b> ${esc(name)}</p><p><b>Email:</b> ${esc(email)}</p>` +
        `<p><b>Phone:</b> ${esc(phone || '-')}</p>` +
        `<p><b>Events:</b><br>${list}</p>` +
        `<p><b>How they can help:</b><br>${esc(message || '-')}</p>`,
    });
  } catch {
    // The sign-up is saved; a lost notification must not fail the form.
  }
}
